<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EntitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('entities')->insert([
            [
                "company_name" => "Reilly Spears Inc",
                "address" => "Dolor dolor voluptas",
                "country" => "Georgia",
                "postal_code" => "Rerum eaque minim a",
                "business_reg_number" => "214",
                "vat_number" => "286",
                "currency" => "JPY",
                "bank_account_name" => "Alma Tyler",
                "bank_account_number" => "788",
                "bank_name" => "Kennan Chang",
                "bank_address" => "Officia ullam ea dol",
                "bank_swift_code" => "",
                "bank_iban_number" => "369",
                "bank_code" => "Fugit nulla enim im",
                "bank_branch_code" => "Atque minus sint acc",
                "is_active" => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                "company_name" => "Celergen International Limited",
                "address" => "Unit 2204, 22/F, Lippo Centre, Tower 2\n89 Queensway\nHong Kong",
                "country" => "China",
                "postal_code" => 12345,
                "business_reg_number" => "1769402",
                "vat_number" => "N/A",
                "currency" => "USD",
                "bank_account_name" => "Celergen International Limited",
                "bank_account_number" => "817-591514-838",
                "bank_name" => "HSBC Hong Kong",
                "bank_address" => "1 Queen's Road Central Hong Kong",
                "bank_swift_code" => "HSBCHKHHHKH",
                "bank_iban_number" => "N/A",
                "bank_code" => "N/A",
                "bank_branch_code" => "N/A",
                "is_active" => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                "company_name" => "Caviarlieri Limited",
                "address" => "2502, 25/F - 148 Electric Road,\nNorth Point,\nHong Kong",
                "country" => "China",
                "postal_code" => 12345,
                "business_reg_number" => "N/A",
                "vat_number" => "N/A",
                "currency" => "USD",
                "bank_account_name" => "Caviarlieri Limited",
                "bank_account_number" => "000578582",
                "bank_name" => "DBS Bank (Hong Kong) Limited",
                "bank_address" => "11th Floor, The Center, 99 Queens's Road\nCentral, Hong Kong",
                "bank_swift_code" => "DHBKHKHH",
                "bank_iban_number" => "N/A",
                "bank_code" => "N/A",
                "bank_branch_code" => "N/A",
                "is_active" => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                "company_name" => "Silicon Apple Pte Ltd",
                "address" => "80 Marine Parade Road\n#13-02, Parkway Parade",
                "country" => "Singapore",
                "postal_code" => "449269",
                "business_reg_number" => "198203957E",
                "vat_number" => "N/A",
                "currency" => "USD",
                "bank_account_name" => "Silicon Apple Pte Ltd",
                "bank_account_number" => "0106121715",
                "bank_name" => "Standard Chartered Bank (Singapore) Limited",
                "bank_address" => "Battery Road Branch, 6 Battery Road, Singapore 049909",
                "bank_swift_code" => "SCBLSG22XXX",
                "bank_iban_number" => "N/A",
                "bank_code" => "N/A",
                "bank_branch_code" => "N/A",
                "is_active" => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                "company_name" => "Caviarlieri Co.,Ltd",
                "address" => "4 Chan16 Yak 12-2 Road\nTungwatdon\nSathorn Bangkok",
                "country" => "Thailand",
                "postal_code" => "10120",
                "business_reg_number" => "N/A",
                "vat_number" => "N/A",
                "currency" => "USD",
                "bank_account_name" => "N/A",
                "bank_account_number" => "411-101523-5",
                "bank_name" => "Siam Commercial Bank (SCB)",
                "bank_address" => "N/A",
                "bank_swift_code" => "N/A",
                "bank_iban_number" => "N/A",
                "bank_code" => "N/A",
                "bank_branch_code" => "N/A",
                "is_active" => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
        ]);
    }
}
